param([string]$Path)
$files = Get-ChildItem -Path $Path -Recurse -Include "*.ts","*.tsx"
Write-Host "Updating $($files.Count) files in $Path"
foreach ($f in $files) {
    $c = Get-Content $f.FullName -Raw
    $c = $c -replace "from '../../services/api'", "from '@/shared/services/api'"
    $c = $c -replace "from '../../../services/api'", "from '@/shared/services/api'"
    $c = $c -replace "from '../../../../services/api'", "from '@/shared/services/api'"
    $c = $c -replace "from '../../../../../services/api'", "from '@/shared/services/api'"
    $c = $c -replace "from '../../../../shared/services/httpClient'", "from '@/shared/services/api'"
    $c = $c -replace "from '../../components/Footer'", "from '@/shared/components/Footer'"
    $c = $c -replace "from '../../components/Modal'", "from '@/shared/components/Modal'"
    $c = $c -replace "from '../../components/ConfirmDialog'", "from '@/shared/components/ConfirmDialog'"
    $c = $c -replace "from '../../components/LoadingSpinner'", "from '@/shared/components/LoadingSpinner'"
    $c = $c -replace "from '../../components/SearchBar'", "from '@/shared/components/SearchBar'"
    $c = $c -replace "from '../../components/EmptyState'", "from '@/shared/components/EmptyState'"
    $c = $c -replace "from '../../components/Button'", "from '@/shared/components/Button'"
    $c = $c -replace "from '../../components/Badge'", "from '@/shared/components/Badge'"
    $c = $c -replace "from '../../components/ProgressBar'", "from '@/shared/components/ProgressBar'"
    $c = $c -replace "from '../../components/StatsCard'", "from '@/shared/components/StatsCard'"
    $c = $c -replace "from '../../components/PageHeader'", "from '@/shared/components/PageHeader'"
    $c = $c -replace "from '../../../components/Modal'", "from '@/shared/components/Modal'"
    $c = $c -replace "from '../../../components/ConfirmDialog'", "from '@/shared/components/ConfirmDialog'"
    $c = $c -replace "from '../../../components/LoadingSpinner'", "from '@/shared/components/LoadingSpinner'"
    $c = $c -replace "from '../../../components/SearchBar'", "from '@/shared/components/SearchBar'"
    $c = $c -replace "from '../../../components/EmptyState'", "from '@/shared/components/EmptyState'"
    $c = $c -replace "from '../../../components/Button'", "from '@/shared/components/Button'"
    $c = $c -replace "from '../../../components/Badge'", "from '@/shared/components/Badge'"
    $c = $c -replace "from '../../../components/ProgressBar'", "from '@/shared/components/ProgressBar'"
    $c = $c -replace "from '../../../components/StatsCard'", "from '@/shared/components/StatsCard'"
    $c = $c -replace "from '../../../components/PageHeader'", "from '@/shared/components/PageHeader'"
    $c = $c -replace "from '../../hooks/useDialog'", "from '@/shared/hooks/useDialog'"
    $c = $c -replace "from '../../../hooks/useDialog'", "from '@/shared/hooks/useDialog'"
    $c = $c -replace "from '../../hooks/useGroups'", "from '@/shared/hooks/useGroups'"
    $c = $c -replace "from '../../hooks/useGroupDetail'", "from '@/shared/hooks/useGroupDetail'"
    $c = $c -replace "from '../../hooks/useParallelDetail'", "from '@/shared/hooks/useParallelDetail'"
    $c = $c -replace "from '../../../hooks/useGroups'", "from '@/shared/hooks/useGroups'"
    $c = $c -replace "from '../../../hooks/useGroupDetail'", "from '@/shared/hooks/useGroupDetail'"
    $c = $c -replace "from '../../../hooks/useParallelDetail'", "from '@/shared/hooks/useParallelDetail'"
    $c = $c -replace "from '../../types/group'", "from '@/shared/types/group'"
    $c = $c -replace "from '../../../types/group'", "from '@/shared/types/group'"
    $c = $c -replace "from '../../../../types/group'", "from '@/shared/types/group'"
    $c = $c -replace "from '../../models/types'", "from '@/shared/models/types'"
    $c = $c -replace "from '../../../models/types'", "from '@/shared/models/types'"
    $c = $c -replace "from './types'", "from '../../../domain/entities'"
    $c = $c -replace "from '../types'", "from '../../../domain/entities'"
    $c = $c -replace "from '../../types'", "from '../../../domain/entities'"
    $c = $c -replace "from './hooks/useAdminData'", "from '../hooks/useAdminData'"
    $c = $c -replace "from './hooks/useAdminModals'", "from '../hooks/useAdminModals'"
    $c = $c -replace "from './hooks/useAdminFilters'", "from '../hooks/useAdminFilters'"
    $c = $c -replace "from './hooks/useTutorData'", "from '../hooks/useTutorData'"
    $c = $c -replace "from './components'", "from '../components'"
    $c = $c -replace "from './components/GroupDetailView'", "from '../components/GroupDetailView'"
    Set-Content $f.FullName $c -NoNewline
}
Write-Host "Done"
