import type { Course, User, Tutoring, Notification, Badge, StudentProgress, DailyProgressReport } from '../models/types';

export const mockUser: User = {
  id: '1',
  name: 'Alex Rivera',
  email: 'alex@krakedev.com',
  role: 'student',
  status: 'active',
  generation: 'Gen 2026-A',
  enrollmentDate: '2026-01-10',
};

export const mockAdmin: User = {
  id: 'admin1',
  name: 'Admin',
  email: 'admin@krakedev.com',
  role: 'admin',
  status: 'active',
};

export const mockTutor: User = {
  id: 'tutor1',
  name: 'Carlos Mendoza',
  email: 'carlos.mendoza@krakedev.com',
  role: 'tutor',
  status: 'active',
};

export const mockBadges: Badge[] = [
  {
    id: 'badge1',
    name: 'JavaScript Fundamentals - Basic',
    description: 'Completaste el bloque básico de JavaScript',
    image: '🥉',
    blockId: 'block1',
    status: 'earned',
    earnedDate: '2026-02-15',
  },
  {
    id: 'badge2',
    name: 'JavaScript Fundamentals - Intermediate',
    description: 'Completaste el bloque intermedio de JavaScript',
    image: '🥈',
    blockId: 'block2',
    status: 'available',
  },
  {
    id: 'badge3',
    name: 'JavaScript Fundamentals - Pro',
    description: 'Completaste el bloque avanzado de JavaScript',
    image: '🥇',
    blockId: 'block3',
    status: 'locked',
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    slug: 'desarrollo-web-full-stack',
    title: 'Desarrollo Web Full Stack',
    description: 'Domina el desarrollo web moderno desde frontend hasta backend',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    progress: 75,
    category: 'DESARROLLO',
    status: 'active',
    minimumPassingGrade: 7,
    tutors: ['tutor1'],
    blocks: [
      {
        id: 'block1',
        name: 'Fundamentos Web',
        order: 1,
        moduleIds: ['m1'],
        expectedProgress: 33,
        requiresTutoring: true,
        minimumPassingGrade: 7,
        badge: mockBadges[0],
        status: 'approved',
      },
      {
        id: 'block2',
        name: 'JavaScript Moderno',
        order: 2,
        moduleIds: ['m2'],
        expectedProgress: 66,
        requiresTutoring: true,
        minimumPassingGrade: 7,
        badge: mockBadges[1],
        status: 'in_progress',
      },
      {
        id: 'block3',
        name: 'React y TypeScript',
        order: 3,
        moduleIds: ['m3'],
        expectedProgress: 100,
        requiresTutoring: true,
        minimumPassingGrade: 7,
        badge: mockBadges[2],
        status: 'locked',
      },
    ],
    modules: [
      {
        id: 'm1',
        title: 'Introducción al Desarrollo Web',
        description: 'Fundamentos del desarrollo web y tecnologías modernas',
        order: 1,
        blockId: 'block1',
        videos: [
          {
            id: 'v1',
            title: '¿Qué es el Desarrollo Web?',
            description: 'Fundamentos del desarrollo web y tecnologías modernas',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '12:30',
            order: 1,
            completed: true,
            locked: false,
            type: 'video',
            dueDate: '2026-02-01',
          },
          {
            id: 'v2',
            title: 'HTML y CSS Moderno',
            description: 'Aprende HTML5 y CSS3 con Flexbox y Grid',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '18:45',
            order: 2,
            completed: true,
            locked: false,
            type: 'video',
            pdfUrl: '/docs/html-css.pdf',
            dueDate: '2026-02-05',
          },
          {
            id: 'd1',
            title: 'Guía de Referencia HTML/CSS',
            description: 'Documento de consulta rápida',
            url: '/docs/html-css-reference.pdf',
            duration: '0:00',
            order: 3,
            completed: false,
            locked: false,
            type: 'document',
            documentData: {
              id: 'doc1',
              title: 'Guía de Referencia HTML/CSS',
              description: 'Documento de consulta rápida para HTML y CSS',
              url: '/docs/html-css-reference.pdf',
              type: 'pdf',
              downloadable: true,
            },
          },
          {
            id: 'c1',
            title: 'Reto 1: Crea tu Primera Página Web',
            description: 'Aplica lo aprendido creando una página web responsive',
            url: '',
            duration: '0:00',
            order: 4,
            completed: true,
            locked: false,
            type: 'challenge',
            dueDate: '2026-02-10',
            challengeData: {
              id: 'ch1',
              instructions: 'Crea una página web responsive utilizando HTML5 y CSS3.',
              criteria: 'Se evaluará: estructura HTML semántica, diseño responsive, uso correcto de CSS.',
              requiresEvidence: true,
              requiresGithubLink: true,
              requiresTutorReview: true,
              dueDate: '2026-02-10',
              submission: {
                id: 'sub1',
                submittedAt: '2026-02-09T14:30:00',
                evidenceUrls: ['https://screenshot1.png', 'https://screenshot2.png'],
                githubLink: 'https://github.com/alexrivera/primera-pagina',
                notes: 'Implementé un diseño moderno con animaciones CSS',
                status: 'approved',
                grade: 9,
                feedback: 'Excelente trabajo! El diseño es limpio y responsive.',
                submittedOnTime: true,
              },
            },
          },
        ],
      },
      {
        id: 'm2',
        title: 'JavaScript Esencial',
        description: 'Domina JavaScript desde cero',
        order: 2,
        blockId: 'block2',
        videos: [
          {
            id: 'v3',
            title: 'Variables y Tipos de Datos',
            description: 'Aprende sobre variables, const, let y tipos de datos',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '22:15',
            order: 1,
            completed: true,
            locked: false,
            type: 'video',
            dueDate: '2026-02-15',
          },
          {
            id: 'v4',
            title: 'Funciones y Arrow Functions',
            description: 'Domina las funciones en JavaScript',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '25:30',
            order: 2,
            completed: false,
            locked: false,
            type: 'video',
            dueDate: '2026-02-20',
          },
          {
            id: 'c2',
            title: 'Reto 2: Calculadora Interactiva',
            description: 'Crea una calculadora funcional con JavaScript',
            url: '',
            duration: '0:00',
            order: 3,
            completed: false,
            locked: false,
            type: 'challenge',
            dueDate: '2026-02-25',
            challengeData: {
              id: 'ch2',
              instructions: 'Desarrolla una calculadora que pueda realizar operaciones básicas.',
              criteria: 'Se evaluará: funcionalidad completa, manejo de errores, diseño de interfaz.',
              requiresEvidence: true,
              requiresGithubLink: true,
              requiresTutorReview: true,
              dueDate: '2026-02-25',
              submission: {
                id: 'sub2',
                submittedAt: '2026-02-24T16:45:00',
                evidenceUrls: ['https://screenshot3.png'],
                githubLink: 'https://github.com/alexrivera/calculadora',
                notes: 'Agregué funcionalidad extra para operaciones avanzadas',
                status: 'submitted',
                submittedOnTime: true,
              },
            },
          },
        ],
      },
      {
        id: 'm3',
        title: 'React y TypeScript',
        description: 'Componentes, hooks y estado en React',
        order: 3,
        blockId: 'block3',
        videos: [
          {
            id: 'v5',
            title: 'Introducción a React',
            description: 'Componentes, hooks y estado en React',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '25:00',
            order: 1,
            completed: false,
            locked: true,
            type: 'video',
            dueDate: '2026-03-01',
          },
        ],
      },
    ],
  },
  {
    id: '2',
    slug: 'aws-cloud-practitioner',
    title: 'Certificación AWS Cloud Practitioner',
    description: 'Prepárate para la certificación AWS y trabaja con nosotros',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    progress: 40,
    category: 'CLOUD',
    status: 'active',
    minimumPassingGrade: 7,
    tutors: ['tutor1'],
    blocks: [],
    modules: [],
  },
  {
    id: '3',
    slug: 'python-data-science',
    title: 'Python para Data Science',
    description: 'Análisis de datos y machine learning con Python',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    progress: 12,
    category: 'DATA',
    status: 'active',
    minimumPassingGrade: 7,
    blocks: [],
    modules: [],
  },
];

export const mockTutorings: Tutoring[] = [
  {
    id: 't1',
    studentId: '1',
    studentName: 'Alex Rivera',
    tutorId: 'tutor1',
    tutorName: 'Carlos Mendoza',
    courseId: '1',
    courseName: 'Desarrollo Web Full Stack',
    blockId: 'block1',
    blockName: 'Fundamentos Web',
    requestDate: '2026-02-10T10:00:00',
    scheduledDate: '2026-02-12',
    scheduledTime: '15:00',
    completedDate: '2026-02-12T15:45:00',
    status: 'completed',
    meetingLink: 'https://zoom.us/j/123456789',
    recordingLink: 'https://zoom.us/rec/123456789',
    grade: 9,
    feedback: 'Excelente dominio de los conceptos.',
    observations: 'Estudiante muy preparado.',
    approved: true,
    attemptNumber: 1,
  },
  {
    id: 't2',
    studentId: '1',
    studentName: 'Alex Rivera',
    tutorId: 'tutor1',
    tutorName: 'Carlos Mendoza',
    courseId: '1',
    courseName: 'Desarrollo Web Full Stack',
    blockId: 'block2',
    blockName: 'JavaScript Moderno',
    requestDate: '2026-02-24T14:30:00',
    scheduledDate: '2026-02-26',
    scheduledTime: '10:00',
    status: 'confirmed',
    meetingLink: 'https://zoom.us/j/987654321',
    attemptNumber: 1,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    userId: '1',
    type: 'tutoring',
    title: 'Tutoría Confirmada',
    message: 'Tu tutoría de JavaScript Moderno ha sido confirmada para el 26 de febrero a las 10:00 AM',
    read: false,
    createdAt: '2026-02-24T15:00:00',
    actionUrl: '/meetings',
  },
  {
    id: 'n2',
    userId: '1',
    type: 'grade',
    title: 'Nueva Calificación',
    message: 'Has recibido una calificación de 9/10 en el Reto 1: Primera Página Web',
    read: false,
    createdAt: '2026-02-13T09:30:00',
  },
  {
    id: 'n3',
    userId: '1',
    type: 'badge',
    title: '¡Nueva Insignia!',
    message: 'Has obtenido la insignia "JavaScript Fundamentals - Basic"',
    read: true,
    createdAt: '2026-02-12T16:00:00',
  },
  {
    id: 'n4',
    userId: '1',
    type: 'deadline',
    title: 'Fecha Límite Próxima',
    message: 'El Reto 2: Calculadora Interactiva vence en 2 días',
    read: false,
    createdAt: '2026-02-23T08:00:00',
  },
];

export const mockStudentProgress: StudentProgress = {
  studentId: '1',
  courseId: '1',
  overallProgress: 75,
  videosCompleted: 3,
  totalVideos: 6,
  challengesSubmitted: 2,
  totalChallenges: 3,
  currentBlock: 'block2',
  blocksCompleted: 1,
  totalBlocks: 3,
  finalGrade: 9,
  badges: [mockBadges[0]],
};

export const mockDailyReports: DailyProgressReport[] = [
  {
    id: 'dr1',
    date: '2026-02-24',
    studentId: '1',
    studentName: 'Alex Rivera',
    courseId: '1',
    courseName: 'Desarrollo Web Full Stack',
    generation: 'Gen 2026-A',
    lastVideoReached: 'Funciones y Arrow Functions',
    overallProgress: 75,
    challengesSubmitted: 2,
    tutoringStatus: 'Tutoría confirmada para 26/02',
    currentBlock: 'JavaScript Moderno',
    observations: 'Buen avance, mantiene el ritmo esperado',
  },
  {
    id: 'dr2',
    date: '2026-02-23',
    studentId: '1',
    studentName: 'Alex Rivera',
    courseId: '1',
    courseName: 'Desarrollo Web Full Stack',
    generation: 'Gen 2026-A',
    lastVideoReached: 'Variables y Tipos de Datos',
    overallProgress: 70,
    challengesSubmitted: 2,
    tutoringStatus: 'Tutoría solicitada',
    currentBlock: 'JavaScript Moderno',
  },
];
