import type { Course, User } from '../models/types';

export const mockUser: User = {
  id: '1',
  name: 'Alex Rivera',
  email: 'alex@krakedev.com',
  role: 'student',
};

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Desarrollo Web Full Stack',
    description: 'Domina el desarrollo web moderno desde frontend hasta backend',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    progress: 75,
    category: 'DESARROLLO',
    modules: [
      {
        id: 'm1',
        title: 'Introducción al Desarrollo Web',
        order: 1,
        videos: [
          {
            id: 'v1',
            title: '¿Qué es el Desarrollo Web?',
            description: 'Fundamentos del desarrollo web y tecnologías modernas',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '12:30',
            order: 1,
            completed: true,
            locked: false,
            type: 'video',
          },
          {
            id: 'v2',
            title: 'HTML y CSS Moderno',
            description: 'Aprende HTML5 y CSS3 con Flexbox y Grid',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '18:45',
            order: 2,
            completed: false,
            locked: false,
            type: 'video',
            pdfUrl: '/docs/html-css.pdf',
          },
          {
            id: 'c1',
            title: 'Reto 1: Crea tu Primera Página Web',
            description: 'Aplica lo aprendido creando una página web responsive',
            url: '',
            duration: '0:00',
            order: 3,
            completed: false,
            locked: false,
            type: 'challenge',
            challengeData: {
              id: 'ch1',
              instructions: 'Crea una página web responsive utilizando HTML5 y CSS3. La página debe incluir: un header con navegación, una sección hero, al menos 3 secciones de contenido, y un footer. Utiliza Flexbox o Grid para el layout.',
              requiresEvidence: true,
              requiresGithubLink: true,
              requiresTutorReview: true,
            },
          },
          {
            id: 'v3',
            title: 'JavaScript Esencial',
            description: 'Domina JavaScript desde cero',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '22:15',
            order: 4,
            completed: false,
            locked: false,
            type: 'video',
          },
        ],
      },
      {
        id: 'm2',
        title: 'React y TypeScript',
        order: 2,
        videos: [
          {
            id: 'v4',
            title: 'Introducción a React',
            description: 'Componentes, hooks y estado en React',
            url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            duration: '25:00',
            order: 1,
            completed: false,
            locked: true,
          },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'Certificación AWS Cloud Practitioner',
    description: 'Prepárate para la certificación AWS y trabaja con nosotros',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    progress: 40,
    category: 'CLOUD',
    modules: [],
  },
  {
    id: '3',
    title: 'Python para Data Science',
    description: 'Análisis de datos y machine learning con Python',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    progress: 12,
    category: 'DATA',
    modules: [],
  },
  {
    id: '4',
    title: 'Bases de Datos y SQL',
    description: 'Diseño y gestión de bases de datos relacionales',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    progress: 0,
    category: 'DATABASE',
    modules: [],
  },
  {
    id: '5',
    title: 'DevOps y CI/CD',
    description: 'Automatización y despliegue continuo',
    image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&q=80',
    progress: 100,
    category: 'DEVOPS',
    modules: [],
  },
];
